# Generated by Django 6.0.4 on 2026-04-24 16:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=10)),
                ('day', models.DateField()),
                ('time_slot', models.TimeField(choices=[(datetime.time(11, 0), '10:00 - 10:30'), (datetime.time(11, 0), '10:30 - 11:00'), (datetime.time(11, 0), '11:00 - 11:30'), (datetime.time(11, 0), '11:30 - 12:00'), (datetime.time(11, 0), '12:00 - 12:30')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'day', 'time_slot'), name='unique_appointment')],
            },
        ),
    ]
