# Generated by Django 5.2.13 on 2026-04-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=10)),
                ('day', models.DateField()),
                ('time_slot', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'day', 'time_slot'), name='unique_appointment_doctor'), models.UniqueConstraint(fields=('patient', 'day', 'time_slot'), name='unique_appointment_patient')],
            },
        ),
    ]
