# Generated by Django 6.0.4 on 2026-04-25 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailibility',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='doctors.doctorprofile'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailibility',
            constraint=models.UniqueConstraint(fields=('doctor', 'days_of_week'), name='unique_availibility'),
        ),
    ]
